version: "3.9"
networks:
  Simple_Web_Network:

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - Simple_Web_Network
    volumes:
      - ./usr/local/mysql:/var/lib/mysql #映射mysql文件，每次重启加载此处文件
      - ./usr/local/mysql/config.cnf:/etc/mysql/my.cnf #挂载mysql配置文件
    environment:
      - "MYSQL_ROOT_PASSWORD=Hwj19991205"
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
  simple_web:
    image: simple-web:1.0.0
    container_name: simple-web
    ports:
      - "8080:8080"
    networks:
      - Simple_Web_Network
