version: "3.9"
networks:
  Simple_Web_Network:

services:
  simple_web:
    image: simple-web:1.0.0
    container_name: simple-web
    ports:
      - "8080:8080"
    networks:
      - Simple_Web_Network
