server:
  port: 8080

spring:
  profiles:
    active: dev
  jackson:
    date-format: YYYY-MM-DD HH:mm:SS
    time-zone: GMT+8

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simplewebdb?useUnicode=true&characterEncoding=UTF-8&useSSL=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    password: Hwj19991205
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.178.87.225:3306/simplewebdb?useUnicode=true&characterEncoding=UTF-8&useSSL=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update